#!/bin/sh

#PBS -V
#PBS -l walltime=00:01:00
#PBS -N Mscalespace
#PBS -j oe
#PBS -q batch
cd $PBS_O_WORKDIR
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64/$LD_LIBRARY_PATH;

mpirun -np 2 -hostfile ./machines ./Combinempicuda 
